# Generated by Django 6.1 on 2026-08-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Frase clave principal para optimizar este contenido.', max_length=100),
        ),
    ]
